import type { ComputedCharacter } from '../../models/character.model';

export const MOCK_COMPUTED_CHARACTER: ComputedCharacter = {
  id: 'mock-1',
  name: 'Theron Valspar',
  playerName: 'Maxime',
  race: {
    raceId: 'elf',
    raceName: 'Elfe',
    subraceId: 'high-elf',
    subraceName: 'Haut-Elfe',
    isHomebrew: false,
  },
  classes: [
    {
      classId: 'wizard',
      className: 'Magicien',
      subclassId: 'evocation',
      subclassName: 'Évocation',
      level: 7,
      isHomebrew: false,
    },
    {
      classId: 'fighter',
      className: 'Guerrier',
      subclassId: 'eldritch-knight',
      subclassName: 'Chevalier Occulte',
      level: 3,
      isHomebrew: false,
    },
  ],
  background: { backgroundId: 'sage', backgroundName: 'Sage', isHomebrew: false },
  alignment: 'Neutre Bon',
  experience: 64000,
  appearance: {
    age: '127',
    height: '1m80',
    weight: '70kg',
    eyes: 'Argent',
    skin: 'Pâle',
    hair: 'Blanc',
  },
  baseAbilityScores: {
    strength: 10,
    dexterity: 16,
    constitution: 14,
    intelligence: 20,
    wisdom: 14,
    charisma: 12,
  },
  computedAbilityScores: {
    strength: 10,
    dexterity: 16,
    constitution: 14,
    intelligence: 22,
    wisdom: 14,
    charisma: 12,
  },
  abilityModifiers: {
    strength: 0,
    dexterity: 3,
    constitution: 2,
    intelligence: 6,
    wisdom: 2,
    charisma: 1,
  },
  skillProficiencies: {
    arcana: 'expert',
    history: 'proficient',
    investigation: 'proficient',
    perception: 'proficient',
  },
  computedSkillBonuses: {
    acrobatics: 3,
    animalHandling: 2,
    arcana: 14,
    athletics: 0,
    deception: 1,
    history: 10,
    insight: 2,
    intimidation: 1,
    investigation: 10,
    medicine: 2,
    nature: 6,
    perception: 6,
    performance: 1,
    persuasion: 1,
    religion: 6,
    sleightOfHand: 3,
    stealth: 3,
    survival: 2,
  },
  savingThrowProficiencies: {
    strength: false,
    dexterity: false,
    constitution: false,
    intelligence: true,
    wisdom: true,
    charisma: false,
  },
  computedSaveBonuses: {
    strength: 0,
    dexterity: 3,
    constitution: 2,
    intelligence: 10,
    wisdom: 6,
    charisma: 1,
  },
  derivedStats: {
    proficiencyBonus: 4,
    initiative: 3,
    armorClass: 14,
    speed: 30,
    hitPointsMax: 82,
    hitPointsCurrent: 82,
    hitPointsTemp: 0,
    hitDice: '7d6+3d10',
    hitDiceRemaining: 10,
    passivePerception: 16,
    passiveInvestigation: 20,
    passiveInsight: 12,
  },
  otherProficiencies: ['Dagues', 'Frondes', 'Bâtons', 'Arbalètes légères'],
  feats: [],
  features: [],
  inventory: [],
  currency: { copper: 0, silver: 50, electrum: 0, gold: 120, platinum: 2 },
  spellcastingAbility: 'intelligence',
  spells: [],
  spellSlots: {
    1: { max: 4, used: 1 },
    2: { max: 3, used: 0 },
    3: { max: 3, used: 1 },
    4: { max: 2, used: 0 },
  },
  attacks: [],
  currentState: {
    hitPoints: 65,
    tempHitPoints: 0,
    hitDiceRemaining: { d6: 5, d10: 3 },
    deathSaves: { successes: 0, failures: 0 },
    exhaustionLevel: 0,
    conditions: [],
    inspiration: true,
  },
  notes: {
    personality: 'Curieux et méthodique, note tout dans son grimoire.',
    ideals: 'La connaissance est le vrai pouvoir.',
    bonds: 'Son grimoire contient les secrets de son maître disparu.',
    flaws: 'Sous-estime les menaces non-magiques.',
    backstory: '',
    allies: '',
    treasure: '',
    other: '',
  },
  activeModifiers: [],
  activeHomebrewRules: [],
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  version: 1,
};
