#!/usr/bin/env node
/**
 * Generates src/environments/environment.prod.ts with values from environment variables.
 * Must run before `ng build` (used as prebuild script).
 *
 * Required env vars (set in Vercel Dashboard):
 *   NG_APP_SUPABASE_URL
 *   NG_APP_SUPABASE_ANON_KEY
 */

const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env['NG_APP_SUPABASE_URL'] || '';
const supabaseAnonKey = process.env['NG_APP_SUPABASE_ANON_KEY'] || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('[set-env] Warning: NG_APP_SUPABASE_URL or NG_APP_SUPABASE_ANON_KEY is not set. Supabase auth will not work.');
}

const content = `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: true,
  supabase: {
    url: '${supabaseUrl}',
    anonKey: '${supabaseAnonKey}',
  },
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.writeFileSync(outPath, content, 'utf8');
console.log('[set-env] environment.prod.ts generated successfully.');
